---
- name: CI/CD Pipeline for Azure ACR (Maveric ECR)
  hosts: docker_servers
  become: yes
  vars:
    acr_name: "mavericECR"  # Azure Container Registry name
    acr_login_server: "mavericecr.azurecr.io"
    acr_username: "your-acr-username"
    acr_password: "your-acr-password"  # Use Ansible Vault for security
    app_directory: "/opt/maveric-app"
    services:
      - auth-service
      - caretaker-service
      - medication-service
      - middleware
      - frontend

  tasks:

    - name: Ensure required packages are installed
      apt:
        name: ['docker.io', 'docker-compose', 'git', 'azure-cli']
        state: present
      when: ansible_os_family == "Debian"

    - name: Log in to Azure ACR
      command: az acr login --name {{ acr_name }}

    - name: Clone the latest application code
      git:
        repo: "https://github.com/your-repo.git"
        dest: "{{ app_directory }}"
        version: "main"
        force: yes

    - name: Build and tag Docker images
      command: >
        docker build -t {{ acr_login_server }}/{{ item }}:latest {{ app_directory }}/microservices/{{ item }}
      with_items: "{{ services }}"

    - name: Push images to Azure ACR
      command: docker push {{ acr_login_server }}/{{ item }}:latest
      with_items: "{{ services }}"

    - name: Stop and remove existing containers
      command: docker-compose down
      args:
        chdir: "{{ app_directory }}"

    - name: Run containers using Docker Compose
      command: docker-compose up -d
      args:
        chdir: "{{ app_directory }}"
