version: "3.8"
services:
  auth-service:
    image: MavericACR.azurecr.io/auth-service:latest
    ports:
      - "4000:4000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - CORS_ORIGIN=http://middleware:3001
    networks:
      - app-network

  caretaker-service:
    image: MavericACR.azurecr.io/caretaker-service:latest
    ports:
      - "4004:4004"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
      - CORS_ORIGIN=http://middleware:3001
    networks:
      - app-network
    depends_on:
      - auth-service

  medication-service:
    image: MavericACR.azurecr.io/medication-service:latest
    ports:
      - "4002:4002"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
      - CORS_ORIGIN=http://middleware:3001
    networks:
      - app-network
    depends_on:
      - auth-service

  middleware:
    image: MavericACR.azurecr.io/middleware:latest
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_SERVICE_URL=http://auth-service:4000
      - CORS_ORIGIN=http://localhost:3000
    networks:
      - app-network
    depends_on:
      - auth-service

  frontend:
    image: MavericACR.azurecr.io/frontend:latest
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - MIDDLEWARE_URL=http://middleware:3001
    networks:
      - app-network
    depends_on:
      - middleware

networks:
  app-network:
    driver: bridge