---
- name: installation
  hosts: all
  become: yes
  tasks:
  
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - curl
          - ca-certificates
          - gnupg
          - lsb-release
        state: present

    - name: Add Microsoft signing key for Azure CLI
      shell: |
        curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

    - name: Add Azure CLI repository
      shell: |
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/azure-cli.list

    - name: Install Azure CLI
      apt:
        name: azure-cli
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
        mode: '0755'


    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version
      changed_when: false

